import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import { Header } from "../components/Header";
import { Sidebar } from "../components/Sidebar";
import { Content } from "../components/Content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "husjon's Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="App">
          <Header />
          <Sidebar />
          <Content>{children}</Content>
        </div>
      </body>
    </html>
  );
}
